import os
import json
import numpy as np
import matplotlib.pyplot as plt
from constants import *


def show_plot_daynight(analysis_scope: str, username: str, userdata: dict[int, int]):
    total_msgs = sum(userdata.values())
    hours = userdata.keys()
    msgs = userdata.values()

    # Generated by ChatGPT. Thanks a lot lol
    day_start = 7
    day_end = 19
    transition = 1
    fig, ax = plt.subplots()
    ax.bar(hours, msgs)
    x = np.linspace(0, 23, 1000)
    y_min, y_max = 0, max(msgs)
    ax.fill_between(x, y_min, y_max,
                    where=(x >= day_start - transition) & (x <= day_end + transition),
                    facecolor='yellow', alpha=0.1, interpolate=True)
    ax.fill_between(x, y_min, y_max,
                    where=(x < day_start - transition) | (x > day_end + transition),
                    facecolor='blue', alpha=0.1, interpolate=True)
    ax.set_title(f"Messages each hour by {username}\nin {analysis_scope}\nTotal Messages: {total_msgs}")
    ax.set_xlabel(f"Hour ({TIMEZONE})")
    ax.set_ylabel("Messages")
    plt.show()


def hourly_of_channel(channel_id: str, username: str):
    for jsonname in os.listdir(JSON_DIRECTORY):
        if channel_id in jsonname:
            with open(f"{JSON_DIRECTORY}/{jsonname}", encoding='utf-8') as f:
                try:
                    channel = Channel(json.load(f))
                except Exception as e:
                    print(e, jsonname)
                break
    userdata = channel.get_hourly_data_of_author(username)
    show_plot_daynight(f"#{channel.name} of server: {channel.server_name}", username, userdata)


def hourly_of_all_channels_in_server(username):
    list_of_channels: list[Channel] = []
    for jsonname in os.listdir(JSON_DIRECTORY):
        with open(f"{JSON_DIRECTORY}/{jsonname}", encoding='utf-8') as f:
            list_of_channels.append(Channel(json.load(f)))
    server = Server(list_of_channels)
    userdata = server.get_hourly_data_of_author_in_server(username)
    show_plot_daynight(f"server: {server.name}", username, userdata)


if __name__ == "__main__":
    pass
